name: Setup Java and Maven
description: Common setup for Java and Maven
inputs:
  GITHUB_TOKEN:
    required: true
    description: "GitHub token for Maven authentication"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configure Maven for GitHub Packages
      shell: bash
      run: |
        mkdir -p ~/.m2
        cat <<EOF > ~/.m2/settings.xml
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ inputs.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF