name: Building Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  build-java-lambda-hello:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'java-lambda-hello')
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build java-lambda-hello
        run: |
          cd lambdas/java-lambda-hello
          mvn deploy

  build-java-lambda-sum:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'java-lambda-sum')
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build java-lambda-sum
        run: |
          cd lambdas/java-lambda-sum
          mvn deploy