name: Building Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  build-java-lambda-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build java-lambda-hello
        run: |
          cd java-lambda-hello
          mvn deploy

  build-java-lambda-sum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build java-lambda-sum
        run: |
          cd java-lambda-sum
          mvn deploy