name: Building Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  build-java-lambda-hello:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'java-lambda-hello')
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build java-lambda-hello
        run: |
          cd lambdas/java-lambda-hello
          mvn deploy

  build-java-lambda-sum:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'java-lambda-sum')
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build java-lambda-sum
        run: |
          cd lambdas/java-lambda-sum
          mvn deploy

  build-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'frontend')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip -y
      - name: Build frontend
        env:
            MY_SECRET: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd frontend
          bash ../deployment/scripts/frontend_build.sh

  build-and-push:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'python-lambda')
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./lambdas/python_lambda
          push: true
          tags: ghcr.io/${{ github.repository }}/python-lambda:latest
          